/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedAppWorkoutsRouteImport } from './routes/_authenticated/_app.workouts'
import { Route as AuthenticatedAppTrainersRouteImport } from './routes/_authenticated/_app.trainers'
import { Route as AuthenticatedAppTrainerPlansRouteImport } from './routes/_authenticated/_app.trainer-plans'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/_app.settings'
import { Route as AuthenticatedAppSearchRouteImport } from './routes/_authenticated/_app.search'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/_app.profile'
import { Route as AuthenticatedAppNutritionRouteImport } from './routes/_authenticated/_app.nutrition'
import { Route as AuthenticatedAppHomeRouteImport } from './routes/_authenticated/_app.home'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated/_app.chat'
import { Route as AuthenticatedAppAiCoachRouteImport } from './routes/_authenticated/_app.ai-coach'
import { Route as AuthenticatedAppUIdRouteImport } from './routes/_authenticated/_app.u.$id'
import { Route as AuthenticatedAppTrainerIdRouteImport } from './routes/_authenticated/_app.trainer.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppWorkoutsRoute =
  AuthenticatedAppWorkoutsRouteImport.update({
    id: '/workouts',
    path: '/workouts',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTrainersRoute =
  AuthenticatedAppTrainersRouteImport.update({
    id: '/trainers',
    path: '/trainers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTrainerPlansRoute =
  AuthenticatedAppTrainerPlansRouteImport.update({
    id: '/trainer-plans',
    path: '/trainer-plans',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSearchRoute = AuthenticatedAppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNutritionRoute =
  AuthenticatedAppNutritionRouteImport.update({
    id: '/nutrition',
    path: '/nutrition',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHomeRoute = AuthenticatedAppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAiCoachRoute = AuthenticatedAppAiCoachRouteImport.update({
  id: '/ai-coach',
  path: '/ai-coach',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppUIdRoute = AuthenticatedAppUIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTrainerIdRoute =
  AuthenticatedAppTrainerIdRouteImport.update({
    id: '/trainer/$id',
    path: '/trainer/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/ai-coach': typeof AuthenticatedAppAiCoachRoute
  '/chat': typeof AuthenticatedAppChatRoute
  '/home': typeof AuthenticatedAppHomeRoute
  '/nutrition': typeof AuthenticatedAppNutritionRoute
  '/profile': typeof AuthenticatedAppProfileRoute
  '/search': typeof AuthenticatedAppSearchRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/trainer-plans': typeof AuthenticatedAppTrainerPlansRoute
  '/trainers': typeof AuthenticatedAppTrainersRoute
  '/workouts': typeof AuthenticatedAppWorkoutsRoute
  '/trainer/$id': typeof AuthenticatedAppTrainerIdRoute
  '/u/$id': typeof AuthenticatedAppUIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/ai-coach': typeof AuthenticatedAppAiCoachRoute
  '/chat': typeof AuthenticatedAppChatRoute
  '/home': typeof AuthenticatedAppHomeRoute
  '/nutrition': typeof AuthenticatedAppNutritionRoute
  '/profile': typeof AuthenticatedAppProfileRoute
  '/search': typeof AuthenticatedAppSearchRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/trainer-plans': typeof AuthenticatedAppTrainerPlansRoute
  '/trainers': typeof AuthenticatedAppTrainersRoute
  '/workouts': typeof AuthenticatedAppWorkoutsRoute
  '/trainer/$id': typeof AuthenticatedAppTrainerIdRoute
  '/u/$id': typeof AuthenticatedAppUIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/_app/ai-coach': typeof AuthenticatedAppAiCoachRoute
  '/_authenticated/_app/chat': typeof AuthenticatedAppChatRoute
  '/_authenticated/_app/home': typeof AuthenticatedAppHomeRoute
  '/_authenticated/_app/nutrition': typeof AuthenticatedAppNutritionRoute
  '/_authenticated/_app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/_app/search': typeof AuthenticatedAppSearchRoute
  '/_authenticated/_app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/_app/trainer-plans': typeof AuthenticatedAppTrainerPlansRoute
  '/_authenticated/_app/trainers': typeof AuthenticatedAppTrainersRoute
  '/_authenticated/_app/workouts': typeof AuthenticatedAppWorkoutsRoute
  '/_authenticated/_app/trainer/$id': typeof AuthenticatedAppTrainerIdRoute
  '/_authenticated/_app/u/$id': typeof AuthenticatedAppUIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/ai-coach'
    | '/chat'
    | '/home'
    | '/nutrition'
    | '/profile'
    | '/search'
    | '/settings'
    | '/trainer-plans'
    | '/trainers'
    | '/workouts'
    | '/trainer/$id'
    | '/u/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/ai-coach'
    | '/chat'
    | '/home'
    | '/nutrition'
    | '/profile'
    | '/search'
    | '/settings'
    | '/trainer-plans'
    | '/trainers'
    | '/workouts'
    | '/trainer/$id'
    | '/u/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/_app'
    | '/_authenticated/_app/ai-coach'
    | '/_authenticated/_app/chat'
    | '/_authenticated/_app/home'
    | '/_authenticated/_app/nutrition'
    | '/_authenticated/_app/profile'
    | '/_authenticated/_app/search'
    | '/_authenticated/_app/settings'
    | '/_authenticated/_app/trainer-plans'
    | '/_authenticated/_app/trainers'
    | '/_authenticated/_app/workouts'
    | '/_authenticated/_app/trainer/$id'
    | '/_authenticated/_app/u/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app/workouts': {
      id: '/_authenticated/_app/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AuthenticatedAppWorkoutsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/trainers': {
      id: '/_authenticated/_app/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof AuthenticatedAppTrainersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/trainer-plans': {
      id: '/_authenticated/_app/trainer-plans'
      path: '/trainer-plans'
      fullPath: '/trainer-plans'
      preLoaderRoute: typeof AuthenticatedAppTrainerPlansRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings': {
      id: '/_authenticated/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/search': {
      id: '/_authenticated/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedAppSearchRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/profile': {
      id: '/_authenticated/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/nutrition': {
      id: '/_authenticated/_app/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AuthenticatedAppNutritionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/home': {
      id: '/_authenticated/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedAppHomeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/chat': {
      id: '/_authenticated/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/ai-coach': {
      id: '/_authenticated/_app/ai-coach'
      path: '/ai-coach'
      fullPath: '/ai-coach'
      preLoaderRoute: typeof AuthenticatedAppAiCoachRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/u/$id': {
      id: '/_authenticated/_app/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof AuthenticatedAppUIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/trainer/$id': {
      id: '/_authenticated/_app/trainer/$id'
      path: '/trainer/$id'
      fullPath: '/trainer/$id'
      preLoaderRoute: typeof AuthenticatedAppTrainerIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAiCoachRoute: typeof AuthenticatedAppAiCoachRoute
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRoute
  AuthenticatedAppHomeRoute: typeof AuthenticatedAppHomeRoute
  AuthenticatedAppNutritionRoute: typeof AuthenticatedAppNutritionRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppSearchRoute: typeof AuthenticatedAppSearchRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTrainerPlansRoute: typeof AuthenticatedAppTrainerPlansRoute
  AuthenticatedAppTrainersRoute: typeof AuthenticatedAppTrainersRoute
  AuthenticatedAppWorkoutsRoute: typeof AuthenticatedAppWorkoutsRoute
  AuthenticatedAppTrainerIdRoute: typeof AuthenticatedAppTrainerIdRoute
  AuthenticatedAppUIdRoute: typeof AuthenticatedAppUIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAiCoachRoute: AuthenticatedAppAiCoachRoute,
  AuthenticatedAppChatRoute: AuthenticatedAppChatRoute,
  AuthenticatedAppHomeRoute: AuthenticatedAppHomeRoute,
  AuthenticatedAppNutritionRoute: AuthenticatedAppNutritionRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppSearchRoute: AuthenticatedAppSearchRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTrainerPlansRoute: AuthenticatedAppTrainerPlansRoute,
  AuthenticatedAppTrainersRoute: AuthenticatedAppTrainersRoute,
  AuthenticatedAppWorkoutsRoute: AuthenticatedAppWorkoutsRoute,
  AuthenticatedAppTrainerIdRoute: AuthenticatedAppTrainerIdRoute,
  AuthenticatedAppUIdRoute: AuthenticatedAppUIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
